spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://shoolStart_db_user:yafajrQuh056dNu9@schoolstartcluster.duh7clz.mongodb.net/SchoolStart?retryWrites=true&w=majority
spring.data.mongodb.database=SchoolStart

server.port=8080

app.jwt.secret=ThisIsMyVerySecretKeyForJwtAuthentication2026Backend
app.jwt.expiration-ms=86400000

file.upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG