spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://shoolStart_db_user:VcSdLI30xs0RcQKw@schoolstartcluster.duh7clz.mongodb.net/?appName=SchoolStartCluster
spring.data.mongodb.database=SchoolStart

server.port=8080

app.jwt.secret=ThisIsMyVerySecretKeyForJwtAuthentication2026Backend
app.jwt.expiration-ms=86400000